// This file is generated by Velite

import config from '../velite.config'

type Collections = typeof config.collections

export type Post = Collections['posts']['schema']['_output']
export declare const posts: Post[]

export type PostMetadata = Collections['postMetadata']['schema']['_output']
export declare const postMetadata: PostMetadata[]

export type Tag = Collections['postTags']['schema']['_output']
export declare const postTags: Tag[]
