// This file is generated by Velite

export { default as posts } from './posts.json'
export { default as postMetadata } from './postMetadata.json'
export { default as postTags } from './postTags.json'
export { default as translations } from './translations.json'
export { default as translationsMetadata } from './translationsMetadata.json'